// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwaofnvmarjcelvlvuza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3YW9mbnZtYXJqY2Vsdmx2dXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjA4NDEsImV4cCI6MjA3MDMzNjg0MX0.59O6juUJzASVKjB7D6tWYMCxFL4tdQYRD4Xd1dlxSuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});